### PR TITLE
new list methods

### PR DESCRIPTION
**Pull request by eredi93**
methods that checks list are missing, datadog changed the way they manage tags and i have to check that a tag is present in the array.
I created:
* list_should_contain
* list_should_not_contain

### CODE REVIEW

**Comment by eredi93** [comment]
@elmundio87 do you think you could get this merged?

**Comment by elmundio87** [comment]
LGTM, thanks for the contribution!

**Comment by elmundio87** [comment]
I've included your changes in the 2.2.0 release

**Comment by eredi93** [comment]
awesome! thx 🚀

**Pull request merged**
